### ISSUE TITLE
'chromedriver' executable may have wrong permissions

### ISSUE THREAD

**Issue by dopaminista** [paeselhz/containarized_selenium_api#1]
It works on local docker build but it gives this error on google cloud run ?

**Comment by paeselhz** [comment]
Hi! Could you share the error that is happening in Google Cloud Run? And, if possible, more details about how you are doing the deployment in GCP.

Thanks!

**Comment by dopaminista** [comment]
Btw thanks for sharing such an useful technology integration stack.

I'm deploying with gcloud sdk shell for windows 10 cmd
`gcloud builds submit --tag gcr.io/PROJECT-ID/SERVICE-NAME`
and
`gcloud run deploy --image gcr.io/PROJECT-ID/SERVICE-NAME`

That's the error that I face with gcloud run

`Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 391, in run_asgi result = await app(self.scope, self.receive, self.send) File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__ return await self.app(scope, receive, send) File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 179, in __call__ await super().__call__(scope, receive, send) File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__ await self.middleware_stack(scope, receive, send) File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__ raise exc from None File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__ await self.app(scope, receive, _send) File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__ raise exc from None File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__ await self.app(scope, receive, sender) File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__ await route.handle(scope, receive, send) File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle await self.app(scope, receive, send) File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app response = await func(request) File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 183, in app dependant=dependant, values=values, is_coroutine=is_coroutine File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 135, in run_endpoint_function return await run_in_threadpool(dependant.call, **values) File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool return await loop.run_in_executor(None, func, *args) File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/app/api/main.py", line 45, in get_product_from_link driver = open_driver() File "/app/api/main.py", line 32, in open_driver './applications/chromedriver', options=chrome_opt) File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__ self.service.start() File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start os.path.basename(self.path), self.start_error_message) selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

**Comment by paeselhz** [comment]
Hi there, sorry for the delay in my response, I just could check on the code today.

So, recently I updated the project through https://github.com/paeselhz/containarized_selenium_api/pull/2, which aims to solve a few problems I encountered with the project... 

The first problem was that Wikipedia changed the format of the table used as an example in this API, so the request wouldn't work even if the chromedriver permissions were set correctly.

Also, I found out that, when using Windows based machines, it is a recurrent problem to copy the files with the wrong permissions (removing the "executability" of chromedriver, i.e.), so I fixed it in Dockerfile, and changed the final COPY statement, where I re-copied everything into the container, to copy only the necessary files for the API.

I tested it on my machine (Linux/Ubuntu 20.04) and it is running, also, I tried the deploy in GCP, and it worked as well, I'm leaving the address of my current deployment below.

https://containerizedseleniumapi-lnefic7smq-ue.a.run.app/docs

Please, if any more trouble arises, let me know and I'll be looking into a solution.

Thanks!
